version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env  # local file with OPENAI_API_KEY
    command: >
      gunicorn -k uvicorn.workers.UvicornWorker main:app
      --bind 0.0.0.0:8000 --workers 4

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000

